title: Project Showcase
description: A portfolio of data science projects
remote_theme: jekyll-theme-minimal

plugins:
  - jekyll-remote-theme

markdown: kramdown

nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

