title: Project Showcase
description: A portfolio of data science projects
theme: cayman

nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

