title: "Project Showcase"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/minimal-mistakes

nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

