title: Project Showcase
description: A portfolio of 10 data science projects
theme: jekyll-theme-primer
url: "https://BADKINS17.github.io/ProjectShowcase"
baseurl: ""            # since deploying from root of repo

nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

